name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        cd /home/runner/work/wireguard-tools/wireguard-tools/src
        make ARCH=arm64
        sudo make install

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wireguard-tools
        path: |
          /usr/bin/wg
          /usr/share/man/man8/wg.8
          /usr/share/bash-completion/completions/wg
          /usr/bin/wg-quick
          /usr/share/man/man8/wg-quick.8
          /usr/share/bash-completion/completions/wg-quick
          /lib/systemd/system/wg-quick.target
          /lib/systemd/system/wg-quick@.service
